// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL =
  (import.meta.env.VITE_SUPABASE_URL as string | undefined)?.trim() ||
  ((import.meta.env.VITE_SUPABASE_PROJECT_ID as string | undefined)?.trim()
    ? `https://${(import.meta.env.VITE_SUPABASE_PROJECT_ID as string).trim()}.supabase.co`
    : undefined);

const SUPABASE_PUBLISHABLE_KEY =
  (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined)?.trim() ||
  (import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined)?.trim();

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  // Avoid crashing with a vague "supabaseUrl is required".
  // This log helps us diagnose missing build-time env vars.
  console.error("[Backend config] Missing required env vars", {
    hasUrl: Boolean(SUPABASE_URL),
    hasKey: Boolean(SUPABASE_PUBLISHABLE_KEY),
  });
}

export const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});